from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['BFIndex', 'Index']
class BFIndex:
    def __init__(self, space: str, dim: typing.SupportsInt) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def add_items(self, data: typing.Any, ids: typing.Any = None) -> None:
        ...
    def delete_vector(self, label: typing.SupportsInt) -> None:
        ...
    def get_current_count(self) -> int:
        ...
    def get_max_elements(self) -> int:
        ...
    def init_index(self, max_elements: typing.SupportsInt) -> None:
        ...
    def knn_query(self, data: typing.Any, k: typing.SupportsInt = 1, num_threads: typing.SupportsInt = -1, filter: collections.abc.Callable[[typing.SupportsInt], bool] = None) -> typing.Any:
        ...
    def load_index(self, path_to_index: str, max_elements: typing.SupportsInt = 0) -> None:
        ...
    def save_index(self, path_to_index: str) -> None:
        ...
    def set_num_threads(self, num_threads: typing.SupportsInt) -> None:
        ...
    @property
    def num_threads(self) -> int:
        ...
    @num_threads.setter
    def num_threads(self, arg0: typing.SupportsInt) -> None:
        ...
class Index:
    def __getstate__(self) -> tuple:
        ...
    @typing.overload
    def __init__(self, params: dict) -> None:
        ...
    @typing.overload
    def __init__(self, index: Index) -> None:
        ...
    @typing.overload
    def __init__(self, space: str, dim: typing.SupportsInt) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def add_items(self, data: typing.Any, ids: typing.Any = None, num_threads: typing.SupportsInt = -1, replace_deleted: bool = False) -> None:
        ...
    def get_current_count(self) -> int:
        ...
    def get_ids_list(self) -> list[int]:
        ...
    def get_items(self, ids: typing.Any = None, return_type: str = 'numpy') -> typing.Any:
        ...
    def get_max_elements(self) -> int:
        ...
    def index_file_size(self) -> int:
        ...
    def init_index(self, max_elements: typing.SupportsInt, M: typing.SupportsInt = 16, ef_construction: typing.SupportsInt = 200, random_seed: typing.SupportsInt = 100, allow_replace_deleted: bool = False) -> None:
        ...
    def knn_query(self, data: typing.Any, k: typing.SupportsInt = 1, num_threads: typing.SupportsInt = -1, filter: collections.abc.Callable[[typing.SupportsInt], bool] = None) -> typing.Any:
        ...
    def load_index(self, path_to_index: str, max_elements: typing.SupportsInt = 0, allow_replace_deleted: bool = False) -> None:
        ...
    def mark_deleted(self, label: typing.SupportsInt) -> None:
        ...
    def resize_index(self, new_size: typing.SupportsInt) -> None:
        ...
    def save_index(self, path_to_index: str) -> None:
        ...
    def set_ef(self, ef: typing.SupportsInt) -> None:
        ...
    def set_num_threads(self, num_threads: typing.SupportsInt) -> None:
        ...
    def unmark_deleted(self, label: typing.SupportsInt) -> None:
        ...
    @property
    def M(self) -> int:
        ...
    @property
    def dim(self) -> int:
        ...
    @property
    def ef(self) -> int:
        ...
    @ef.setter
    def ef(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def ef_construction(self) -> int:
        ...
    @property
    def element_count(self) -> int:
        ...
    @property
    def max_elements(self) -> int:
        ...
    @property
    def num_threads(self) -> int:
        ...
    @num_threads.setter
    def num_threads(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def space(self) -> str:
        ...
