from __future__ import annotations
import argus_synchro_lib.octotree
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['AbstractCollisionDetectorBaseInt', 'AbstractCollisionDetectorBaseTupleIntIntInt', 'CollisionDetResult', 'CoordMethod', 'FAR_POINT', 'LayerBasedCollisionDetector', 'MEAN', 'NEAR_POINT', 'NeighborBasedCollisionDetector', 'QUANTILE', 'VOX_MED']
class AbstractCollisionDetectorBaseInt:
    coord_method: CoordMethod
    octotree_obj: argus_synchro_lib.octotree.OctoTree | None
    def __init__(self, coord_method: CoordMethod = CoordMethod.VOX_MED) -> None:
        ...
    def _far2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def _get_vox_w_pairs(self, src_nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], dest_nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"], typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]]:
        ...
    def _keynode2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"]:
        ...
    def _mean2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def _near2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def _quantile2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def assign_octotree(self, octotree_obj: argus_synchro_lib.octotree.OctoTree) -> AbstractCollisionDetectorBaseInt:
        ...
    def collision_detection(self, src_coords: collections.abc.Set[typing.SupportsInt | typing.SupportsIndex], dest_coords: collections.abc.Set[typing.SupportsInt | typing.SupportsIndex]) -> bool:
        ...
    def create_dest_coord(self, nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], window: typing.SupportsInt | typing.SupportsIndex = 2) -> set[int]:
        ...
    def create_dialation_coord(self, nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], window: typing.SupportsInt | typing.SupportsIndex = 2) -> set[int]:
        ...
    def detect_collided_object(self, src_detect_label: str, src_measure_label: str, dest_labels: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = None, window: typing.SupportsInt | typing.SupportsIndex = 2, detect_window: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] | None = ..., distance_threshold: typing.SupportsFloat | typing.SupportsIndex | None = 10.0, metric: collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]], float] | None = None) -> dict[int | str, CollisionDetResult]:
        ...
    def find_minimum_node_pair(self, src_nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], dest_nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], distance_threshold: typing.SupportsFloat | typing.SupportsIndex | None, metric: collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]], float] | None = None) -> argus_synchro_lib.collision_detector.CollisionDetResult | None:
        ...
class AbstractCollisionDetectorBaseTupleIntIntInt:
    coord_method: CoordMethod
    octotree_obj: argus_synchro_lib.octotree.OctoTree | None
    def __init__(self, coord_method: CoordMethod = CoordMethod.VOX_MED) -> None:
        ...
    def _far2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def _get_vox_w_pairs(self, src_nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], dest_nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"], typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]]:
        ...
    def _keynode2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"]:
        ...
    def _mean2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def _near2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def _quantile2array(self, keynodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def assign_octotree(self, octotree_obj: argus_synchro_lib.octotree.OctoTree) -> AbstractCollisionDetectorBaseTupleIntIntInt:
        ...
    def collision_detection(self, src_coords: collections.abc.Set[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], dest_coords: collections.abc.Set[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]]) -> bool:
        ...
    def create_dest_coord(self, nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], window: typing.SupportsInt | typing.SupportsIndex = 2) -> set[tuple[int, int, int]]:
        ...
    def create_dialation_coord(self, nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], window: typing.SupportsInt | typing.SupportsIndex = 2) -> set[tuple[int, int, int]]:
        ...
    def detect_collided_object(self, src_detect_label: str, src_measure_label: str, dest_labels: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = None, window: typing.SupportsInt | typing.SupportsIndex = 2, detect_window: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] | None = ..., distance_threshold: typing.SupportsFloat | typing.SupportsIndex | None = 10.0, metric: collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]], float] | None = None) -> dict[int | str, CollisionDetResult]:
        ...
    def find_minimum_node_pair(self, src_nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], dest_nodes: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], argus_synchro_lib.octotree.OctoNode], distance_threshold: typing.SupportsFloat | typing.SupportsIndex | None, metric: collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]], float] | None = None) -> argus_synchro_lib.collision_detector.CollisionDetResult | None:
        ...
class CollisionDetResult:
    dest_node: argus_synchro_lib.octotree.OctoNode
    src_node: argus_synchro_lib.octotree.OctoNode
    def __init__(self, arg0: argus_synchro_lib.octotree.OctoNode, arg1: argus_synchro_lib.octotree.OctoNode, arg2: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], arg3: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], arg4: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __repr__(self) -> dict:
        ...
    def to_dict(self) -> dict:
        ...
    def to_tuple(self) -> tuple[argus_synchro_lib.octotree.OctoNode, argus_synchro_lib.octotree.OctoNode, tuple[float, float, float], tuple[float, float, float], float]:
        ...
    @property
    def dest_coord(self) -> tuple[float, float, float]:
        ...
    @dest_coord.setter
    def dest_coord(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def src_coord(self) -> tuple[float, float, float]:
        ...
    @src_coord.setter
    def src_coord(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def src_dest_dist(self) -> float:
        ...
    @src_dest_dist.setter
    def src_dest_dist(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class CoordMethod:
    """
    Members:
    
      VOX_MED
    
      MEAN
    
      FAR_POINT
    
      NEAR_POINT
    
      QUANTILE
    """
    FAR_POINT: typing.ClassVar[CoordMethod]  # value = <CoordMethod.FAR_POINT: 2>
    MEAN: typing.ClassVar[CoordMethod]  # value = <CoordMethod.MEAN: 1>
    NEAR_POINT: typing.ClassVar[CoordMethod]  # value = <CoordMethod.NEAR_POINT: 3>
    QUANTILE: typing.ClassVar[CoordMethod]  # value = <CoordMethod.QUANTILE: 4>
    VOX_MED: typing.ClassVar[CoordMethod]  # value = <CoordMethod.VOX_MED: 0>
    __members__: typing.ClassVar[dict[str, CoordMethod]]  # value = {'VOX_MED': <CoordMethod.VOX_MED: 0>, 'MEAN': <CoordMethod.MEAN: 1>, 'FAR_POINT': <CoordMethod.FAR_POINT: 2>, 'NEAR_POINT': <CoordMethod.NEAR_POINT: 3>, 'QUANTILE': <CoordMethod.QUANTILE: 4>}
    @staticmethod
    def from_string(name: str) -> CoordMethod:
        ...
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class LayerBasedCollisionDetector(AbstractCollisionDetectorBaseInt):
    def __init__(self, coord_method: CoordMethod = CoordMethod.VOX_MED) -> None:
        ...
class NeighborBasedCollisionDetector(AbstractCollisionDetectorBaseTupleIntIntInt):
    def __init__(self, coord_method: CoordMethod = CoordMethod.VOX_MED) -> None:
        ...
FAR_POINT: CoordMethod  # value = <CoordMethod.FAR_POINT: 2>
MEAN: CoordMethod  # value = <CoordMethod.MEAN: 1>
NEAR_POINT: CoordMethod  # value = <CoordMethod.NEAR_POINT: 3>
QUANTILE: CoordMethod  # value = <CoordMethod.QUANTILE: 4>
VOX_MED: CoordMethod  # value = <CoordMethod.VOX_MED: 0>
