from __future__ import annotations
import argus_synchro_lib.collision_detector
import argus_synchro_lib.machine_collision
import argus_synchro_lib.octotree
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['OctotreeCollisionConfig', 'OctotreeCollisionConfigBuilder', 'octotree_accum_points', 'octotree_collision_detection', 'octotree_collision_detection_entities', 'remove_machine_points', 'rotate_x', 'rotate_xyz', 'rotate_y', 'rotate_z', 'transfer_movable_octotree', 'update_movable_entity']
class OctotreeCollisionConfig:
    dest_entity: argus_synchro_lib.octotree.NodeEntity
    metric: collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]], float] | None
    octotree_obj: argus_synchro_lib.octotree.OctoTree
    def __init__(self) -> None:
        ...
    @property
    def dest_labels(self) -> list[int | None] | None:
        ...
    @dest_labels.setter
    def dest_labels(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex | None] | None) -> None:
        ...
    @property
    def detect_window(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"] | None:
        ...
    @detect_window.setter
    def detect_window(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] | None) -> None:
        ...
    @property
    def dialate_point_size(self) -> int:
        ...
    @dialate_point_size.setter
    def dialate_point_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def distance_threshold(self) -> float | None:
        ...
    @distance_threshold.setter
    def distance_threshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex | None) -> None:
        ...
    @property
    def pitch_angle(self) -> float:
        ...
    @pitch_angle.setter
    def pitch_angle(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def roll_angle(self) -> float:
        ...
    @roll_angle.setter
    def roll_angle(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def src_detect_entities(self) -> list[argus_synchro_lib.octotree.NodeEntity]:
        ...
    @src_detect_entities.setter
    def src_detect_entities(self, arg0: collections.abc.Sequence[argus_synchro_lib.octotree.NodeEntity]) -> None:
        ...
    @property
    def src_labels(self) -> list[int | None] | None:
        ...
    @src_labels.setter
    def src_labels(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex | None] | None) -> None:
        ...
    @property
    def src_measure_entities(self) -> list[argus_synchro_lib.octotree.NodeEntity]:
        ...
    @src_measure_entities.setter
    def src_measure_entities(self, arg0: collections.abc.Sequence[argus_synchro_lib.octotree.NodeEntity]) -> None:
        ...
    @property
    def yaw_angle(self) -> float:
        ...
    @yaw_angle.setter
    def yaw_angle(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class OctotreeCollisionConfigBuilder:
    def __init__(self, dest_entity: argus_synchro_lib.octotree.NodeEntity = argus_synchro_lib.octotree.NodeEntity.OTHER) -> None:
        ...
    def build(self) -> OctotreeCollisionConfig:
        ...
    def setAngles(self, roll_rad: typing.SupportsFloat | typing.SupportsIndex = 0.0, pitch_rad: typing.SupportsFloat | typing.SupportsIndex = 0.0, yaw_rad: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> OctotreeCollisionConfigBuilder:
        ...
    def setDestLabels(self, dest_labels: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex | None] | None = None) -> OctotreeCollisionConfigBuilder:
        ...
    def setDetectWindow(self, detect_window: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] | None = ...) -> OctotreeCollisionConfigBuilder:
        ...
    def setDialatePointSize(self, dialate_point_size: typing.SupportsInt | typing.SupportsIndex = 5) -> OctotreeCollisionConfigBuilder:
        ...
    def setDistanceThreshold(self, distance_threshold: typing.SupportsFloat | typing.SupportsIndex | None = 10.0) -> OctotreeCollisionConfigBuilder:
        ...
    def setOctotree(self, octotree_obj: argus_synchro_lib.octotree.OctoTree) -> OctotreeCollisionConfigBuilder:
        ...
    def setSrcDetectEntities(self, src_detect_entities: collections.abc.Sequence[argus_synchro_lib.octotree.NodeEntity]) -> OctotreeCollisionConfigBuilder:
        ...
    def setSrcLabels(self, src_labels: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex | None] | None = None) -> OctotreeCollisionConfigBuilder:
        ...
    def setSrcMeasureEntities(self, src_measure_entities: collections.abc.Sequence[argus_synchro_lib.octotree.NodeEntity]) -> OctotreeCollisionConfigBuilder:
        ...
def octotree_accum_points(pcd_points: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], octotree_pcd: argus_synchro_lib.octotree.OctoTree, target_entity: argus_synchro_lib.octotree.NodeEntity = argus_synchro_lib.octotree.NodeEntity.OTHER, point_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"], argus_synchro_lib.octotree.OctoTree]:
    ...
@typing.overload
def octotree_collision_detection(octotree_pcd: argus_synchro_lib.octotree.OctoTree, octotree_machine_mobile_detect: argus_synchro_lib.octotree.OctoTree, octotree_machine_immobile_detect: argus_synchro_lib.octotree.OctoTree, machine_mobile_points_detect: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], octotree_machine_mobile_measure: argus_synchro_lib.octotree.OctoTree, octotree_machine_immobile_measure: argus_synchro_lib.octotree.OctoTree, machine_mobile_points_measure: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], collision_detector: argus_synchro_lib.collision_detector.LayerBasedCollisionDetector, dest_labels: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = None, dialate_point_size: typing.SupportsInt | typing.SupportsIndex = 2, detect_window: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] | None = ..., roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, distance_threshold: typing.SupportsFloat | typing.SupportsIndex | None = 10.0, metric: collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]], float] | None = None) -> tuple[dict[int | str, argus_synchro_lib.collision_detector.CollisionDetResult], argus_synchro_lib.octotree.OctoTree, argus_synchro_lib.octotree.OctoTree, argus_synchro_lib.octotree.OctoTree]:
    ...
@typing.overload
def octotree_collision_detection(octotree_pcd: argus_synchro_lib.octotree.OctoTree, octotree_machine_mobile_detect: argus_synchro_lib.octotree.OctoTree, octotree_machine_immobile_detect: argus_synchro_lib.octotree.OctoTree, machine_mobile_points_detect: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], octotree_machine_mobile_measure: argus_synchro_lib.octotree.OctoTree, octotree_machine_immobile_measure: argus_synchro_lib.octotree.OctoTree, machine_mobile_points_measure: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], collision_detector: argus_synchro_lib.collision_detector.NeighborBasedCollisionDetector, dest_labels: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = None, dialate_point_size: typing.SupportsInt | typing.SupportsIndex = 2, detect_window: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] | None = ..., roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, distance_threshold: typing.SupportsFloat | typing.SupportsIndex | None = 10.0, metric: collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]], float] | None = None) -> tuple[dict[int | str, argus_synchro_lib.collision_detector.CollisionDetResult], argus_synchro_lib.octotree.OctoTree, argus_synchro_lib.octotree.OctoTree, argus_synchro_lib.octotree.OctoTree]:
    ...
@typing.overload
def octotree_collision_detection_entities(collision_detector: argus_synchro_lib.collision_detector.LayerBasedCollisionDetector, cfg: OctotreeCollisionConfig) -> dict[int | None, argus_synchro_lib.collision_detector.CollisionDetResult]:
    ...
@typing.overload
def octotree_collision_detection_entities(collision_detector: argus_synchro_lib.collision_detector.NeighborBasedCollisionDetector, cfg: OctotreeCollisionConfig) -> dict[int | None, argus_synchro_lib.collision_detector.CollisionDetResult]:
    ...
def remove_machine_points(pcd_points: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], l_machine_col: collections.abc.Sequence[argus_synchro_lib.machine_collision.MachineCollisionBase], remove_dist: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] | None = (0.11, 0.11, 0.11), roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
    ...
def rotate_x(theta: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def rotate_xyz(roll_rad_angle: typing.SupportsFloat | typing.SupportsIndex, pitch_rad_angle: typing.SupportsFloat | typing.SupportsIndex, yaw_rad_angle: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def rotate_y(theta: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def rotate_z(theta: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def transfer_movable_octotree(octotree_obj: argus_synchro_lib.octotree.OctoTree, octotree_points: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> argus_synchro_lib.octotree.OctoTree:
    ...
def update_movable_entity(octotree_obj: argus_synchro_lib.octotree.OctoTree, octotree_points: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], transfered_entity: argus_synchro_lib.octotree.NodeEntity, entity_replace: bool = True, roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> argus_synchro_lib.octotree.OctoTree:
    ...
