from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['Camera', 'CameraDetectionData']
class Camera:
    def __getstate__(self) -> dict[str, typing.Any]:
        ...
    def __init__(self, cam_index: typing.SupportsInt | typing.SupportsIndex, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, rvec: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], tvec: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], ncm1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], extrmat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]) -> None:
        ...
    def __setstate__(self, arg0: dict[str, typing.Any]) -> None:
        ...
    @property
    def cam_index(self) -> int:
        ...
    @cam_index.setter
    def cam_index(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def extrmat(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    @extrmat.setter
    def extrmat(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]) -> None:
        ...
    @property
    def height(self) -> int:
        ...
    @height.setter
    def height(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def ncm1(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @ncm1.setter
    def ncm1(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @property
    def rvec(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @rvec.setter
    def rvec(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
        ...
    @property
    def tvec(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @tvec.setter
    def tvec(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @property
    def width(self) -> int:
        ...
    @width.setter
    def width(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class CameraDetectionData:
    def __getstate__(self) -> dict[str, typing.Any]:
        ...
    def __init__(self, boxes: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"], scores: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"], classes: typing.Annotated[numpy.typing.ArrayLike, numpy.int64, "[m, n]"], valid_detects: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __setstate__(self, arg0: dict[str, typing.Any]) -> None:
        ...
    @property
    def boxes(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
        ...
    @boxes.setter
    def boxes(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> None:
        ...
    @property
    def classes(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int64], "[m, n]"]:
        ...
    @classes.setter
    def classes(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.int64, "[m, n]"]) -> None:
        ...
    @property
    def scores(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
        ...
    @scores.setter
    def scores(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> None:
        ...
    @property
    def valid_detects(self) -> int:
        ...
    @valid_detects.setter
    def valid_detects(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
