from __future__ import annotations
import argus_synchro_lib.octotree
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['AggName', 'BevCoord', 'CARTESIAN', 'DediscretizeMethod', 'EdgeDetectionConfig', 'EdgeDetectionResult', 'EdgeDetector', 'LAST', 'MAX', 'MEAN', 'MED', 'MIN', 'POLAR', 'cartesian_to_polar', 'grid_to_real', 'mask_img_by_value', 'octotree2bev', 'polar_to_cartesian', 'real_to_grid', 'scale_value']
class AggName:
    """
    Members:
    
      MEAN
    
      MAX
    
      MIN
    
      LAST
    """
    LAST: typing.ClassVar[AggName]  # value = <AggName.LAST: 3>
    MAX: typing.ClassVar[AggName]  # value = <AggName.MAX: 1>
    MEAN: typing.ClassVar[AggName]  # value = <AggName.MEAN: 0>
    MIN: typing.ClassVar[AggName]  # value = <AggName.MIN: 2>
    __members__: typing.ClassVar[dict[str, AggName]]  # value = {'MEAN': <AggName.MEAN: 0>, 'MAX': <AggName.MAX: 1>, 'MIN': <AggName.MIN: 2>, 'LAST': <AggName.LAST: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class BevCoord:
    """
    Members:
    
      CARTESIAN
    
      POLAR
    """
    CARTESIAN: typing.ClassVar[BevCoord]  # value = <BevCoord.CARTESIAN: 0>
    POLAR: typing.ClassVar[BevCoord]  # value = <BevCoord.POLAR: 1>
    __members__: typing.ClassVar[dict[str, BevCoord]]  # value = {'CARTESIAN': <BevCoord.CARTESIAN: 0>, 'POLAR': <BevCoord.POLAR: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class DediscretizeMethod:
    """
    Members:
    
      MED
    
      MIN
    
      MAX
    """
    MAX: typing.ClassVar[DediscretizeMethod]  # value = <DediscretizeMethod.MAX: 2>
    MED: typing.ClassVar[DediscretizeMethod]  # value = <DediscretizeMethod.MED: 0>
    MIN: typing.ClassVar[DediscretizeMethod]  # value = <DediscretizeMethod.MIN: 1>
    __members__: typing.ClassVar[dict[str, DediscretizeMethod]]  # value = {'MED': <DediscretizeMethod.MED: 0>, 'MIN': <DediscretizeMethod.MIN: 1>, 'MAX': <DediscretizeMethod.MAX: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class EdgeDetectionConfig:
    def __init__(self, target_edge_dist_th: typing.SupportsFloat | typing.SupportsIndex = 20.0) -> None:
        ...
    @property
    def target_edge_dist_th(self) -> float:
        ...
class EdgeDetectionResult:
    def __init__(self, frame: typing.SupportsInt | typing.SupportsIndex, time: typing.SupportsFloat | typing.SupportsIndex, edge_points: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], edge_lines: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], edge_lenth: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[m, 1]"]) -> None:
        ...
    def get_edge_cluster(self) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"], typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]]:
        ...
    def get_edge_points_on_ground(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @property
    def edge_length(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def edge_lines(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @property
    def edge_points(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @property
    def frame(self) -> int:
        ...
    @property
    def time(self) -> float:
        ...
class EdgeDetector:
    def __init__(self) -> None:
        ...
    def main(self, octotree_obj: argus_synchro_lib.octotree.OctoTree, target_entities: collections.abc.Sequence[argus_synchro_lib.octotree.NodeEntity]) -> EdgeDetectionResult:
        ...
    def update(self, edge_conf: EdgeDetectionConfig) -> None:
        ...
def cartesian_to_polar(points: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], polar_origin: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
    ...
def grid_to_real(grid_coords_2d: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[m, n]"], grid_size: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], grid_offset: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex] = (0, 0), real_offset: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.0, 0.0), repr_method: DediscretizeMethod = DediscretizeMethod.MED) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
    ...
def mask_img_by_value(src: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8, "[m, n]"], low_value: typing.SupportsFloat | typing.SupportsIndex = 50.0, high_value: typing.SupportsFloat | typing.SupportsIndex = 200.0) -> typing.Annotated[numpy.typing.NDArray[numpy.int8], "[m, n]"]:
    ...
def octotree2bev(octotree_obj: argus_synchro_lib.octotree.OctoTree, fwd_range: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], side_range: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], grid_size: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], bev_shape: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], target_entities: collections.abc.Sequence[argus_synchro_lib.octotree.NodeEntity], bev_depth: typing.SupportsInt | typing.SupportsIndex | None = None, bev_coord: BevCoord = BevCoord.POLAR, agg_method: AggName = AggName.MAX, coord_origin: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0, 0, 0), discrete_origin: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0, -3.141592653589793), scaled: bool = True, min_scale_z: typing.SupportsFloat | typing.SupportsIndex = -1.88, max_scale_z: typing.SupportsFloat | typing.SupportsIndex = -0.88, min_bev_val: typing.SupportsFloat | typing.SupportsIndex = 0.0, max_bev_val: typing.SupportsFloat | typing.SupportsIndex = 255.0, nan_fill_value: typing.SupportsInt | typing.SupportsIndex = 0) -> typing.Annotated[numpy.typing.NDArray[numpy.uint8], "[m, n]"]:
    ...
def polar_to_cartesian(real_polar_coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], from_polar_origin: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
    ...
def real_to_grid(real_coords_2d: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], grid_size: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], real_offset: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.0, 0.0), grid_offset: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex] = (0, 0)) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"]:
    ...
def scale_value(mat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], from_min: typing.SupportsFloat | typing.SupportsIndex, from_max: typing.SupportsFloat | typing.SupportsIndex, to_min: typing.SupportsFloat | typing.SupportsIndex = 0.0, to_max: typing.SupportsFloat | typing.SupportsIndex = 255.0) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
    ...
CARTESIAN: BevCoord  # value = <BevCoord.CARTESIAN: 0>
LAST: AggName  # value = <AggName.LAST: 3>
MAX: AggName  # value = <AggName.MAX: 1>
MEAN: AggName  # value = <AggName.MEAN: 0>
MED: DediscretizeMethod  # value = <DediscretizeMethod.MED: 0>
MIN: AggName  # value = <AggName.MIN: 2>
POLAR: BevCoord  # value = <BevCoord.POLAR: 1>
