"""
pybind11 bindings for error_mmap_writer
"""
from __future__ import annotations
import collections.abc
import typing
import typing_extensions
__all__: list[str] = ['ErrorMMapWriter']
class ErrorMMapWriter:
    def __init__(self, paths: collections.abc.Sequence[str], logfunc: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex, str], None]) -> None:
        ...
    def close(self) -> None:
        ...
    def init(self) -> None:
        ...
    def rotate_if_busy(self) -> None:
        ...
    def start_write(self) -> None:
        ...
    def write_action_error(self, data: typing_extensions.Buffer) -> None:
        ...
    def write_state_error(self, data: typing_extensions.Buffer) -> None:
        ...
    def write_status(self, data: typing_extensions.Buffer) -> None:
        ...
