from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['BaseRange', 'CircumcenterProcessor', 'CuboidRange', 'MachineCollisionBase', 'MachineCollisionImmobileCuboid', 'MachineCollisionImmobileHexaPrism', 'MachineCollisionImmobileRoundCuboid', 'MachineCollisionMobileCuboid', 'MachineConf', 'TriPillar', 'create_base_range_from_json', 'create_machine_collision_list', 'load_base_ranges_from_json']
class BaseRange:
    def check_pcd(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], remove_dist: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.12, 0.12, 0.04)) -> typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]:
        ...
class CircumcenterProcessor:
    def __init__(self) -> None:
        ...
    def fit(self, points: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> CircumcenterProcessor:
        ...
    def score(self, points: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], center: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], radius: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @property
    def center(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"] | None:
        ...
    @center.setter
    def center(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"] | None) -> None:
        ...
    @property
    def points(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
        ...
    @points.setter
    def points(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> None:
        ...
    @property
    def radius(self) -> float | None:
        ...
    @radius.setter
    def radius(self, arg0: typing.SupportsFloat | typing.SupportsIndex | None) -> None:
        ...
class CuboidRange(BaseRange):
    def __init__(self, x_min_max: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], y_min_max: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], z_min_max: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], x_range_ratio: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (-1.0, 1.0), y_range_ratio: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (-1.0, 1.0), z_range_ratio: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (-1.0, 1.0)) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def check_pcd(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], remove_dist: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.12, 0.12, 0.04)) -> typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]:
        ...
    @property
    def x_minmax(self) -> tuple[float, float]:
        ...
    @x_minmax.setter
    def x_minmax(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def x_range_ratio(self) -> tuple[float, float]:
        ...
    @x_range_ratio.setter
    def x_range_ratio(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def y_minmax(self) -> tuple[float, float]:
        ...
    @y_minmax.setter
    def y_minmax(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def y_range_ratio(self) -> tuple[float, float]:
        ...
    @y_range_ratio.setter
    def y_range_ratio(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def z_minmax(self) -> tuple[float, float]:
        ...
    @z_minmax.setter
    def z_minmax(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def z_range_ratio(self) -> tuple[float, float]:
        ...
    @z_range_ratio.setter
    def z_range_ratio(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
class MachineCollisionBase:
    machine_info: MachineConf
    pcd_points_file: str
    reverse_initial: tuple[bool, bool, bool]
    def __init__(self, machine_info: MachineConf, filename: str, initial_offsets: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] | None = None, reverse: tuple[bool, bool, bool] | None = None, machine_form_extension: str = '.csv') -> None:
        ...
    def __str__(self) -> str:
        ...
    def check_pcd_on_self(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], remove_dist: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.11, 0.11, 0.11), roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0, transform_mat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"] | None = 0) -> typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]:
        ...
    @property
    def machine_form_points(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @machine_form_points.setter
    def machine_form_points(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
        ...
    @property
    def machine_pcd_points(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @machine_pcd_points.setter
    def machine_pcd_points(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
        ...
    @property
    def offsets_initial(self) -> tuple[float, float, float]:
        ...
    @offsets_initial.setter
    def offsets_initial(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
class MachineCollisionImmobileCuboid(MachineCollisionBase):
    def __init__(self, machine_info: MachineConf, filename: str, initial_offsets: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] | None = None, reverse: tuple[bool, bool, bool] | None = None) -> None:
        ...
    def check_pcd_on_self(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], remove_dist: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.11, 0.11, 0.11), roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0, transform_mat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"] | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]:
        ...
class MachineCollisionImmobileHexaPrism(MachineCollisionBase):
    def __init__(self, machine_info: MachineConf, filename: str, initial_offsets: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] | None = None, reverse: tuple[bool, bool, bool] | None = None, machine_form_extension: str = '.jsonc') -> None:
        ...
    def check_pcd_on_self(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], remove_dist: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.11, 0.11, 0.11), roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0, transform_mat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"] | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]:
        ...
    @property
    def hex_base_ranges(self) -> list:
        ...
class MachineCollisionImmobileRoundCuboid(MachineCollisionBase):
    def __init__(self, machine_info: MachineConf, filename: str, initial_offsets: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] | None = None, reverse: tuple[bool, bool, bool] | None = None) -> None:
        ...
    def check_pcd_on_self(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], remove_dist: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.11, 0.11, 0.11), roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0, transform_mat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"] | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]:
        ...
class MachineCollisionMobileCuboid(MachineCollisionBase):
    def __init__(self, machine_info: MachineConf, filename: str, initial_offsets: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] | None = None, reverse: tuple[bool, bool, bool] | None = None) -> None:
        ...
    def check_pcd_on_self(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], remove_dist: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.11, 0.11, 0.11), roll_angle: typing.SupportsFloat | typing.SupportsIndex = 0, pitch_angle: typing.SupportsFloat | typing.SupportsIndex = 0, yaw_angle: typing.SupportsFloat | typing.SupportsIndex = 0, transform_mat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"] | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]:
        ...
class MachineConf:
    form_points_pattern: str
    instance_name: str
    is_mobile: bool
    pcd_points_file: str
    reverse: tuple[bool, bool, bool]
    def __init__(self, pcd_points_file: str, load_order: typing.SupportsInt | typing.SupportsIndex, instance_name: str, offsets: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0, 0, 0), reverse: tuple[bool, bool, bool] = (False, True, False), is_mobile: bool = False, form_points_pattern: str = 'cuboid_points') -> None:
        ...
    def get_form_points_filename(self, filename: str, extension: str = '.csv') -> str:
        ...
    @property
    def load_order(self) -> int:
        ...
    @load_order.setter
    def load_order(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def offsets(self) -> tuple[float, float, float]:
        ...
    @offsets.setter
    def offsets(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
class TriPillar(BaseRange):
    vec_is_reverse: bool
    def __init__(self, z_minmax: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], tri_points: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]], x_remove_offset_ratio: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], y_remove_offset_ratio: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], z_remove_offset_ratio: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], vec_is_reverse: bool = False) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def check_pcd(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], remove_dist: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex] = (0.12, 0.12, 0.04)) -> typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]:
        ...
    @property
    def tri_points(self) -> list[tuple[float, float]]:
        ...
    @tri_points.setter
    def tri_points(self, arg0: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]) -> None:
        ...
    @property
    def x_remove_offset_ratio(self) -> tuple[float, float]:
        ...
    @x_remove_offset_ratio.setter
    def x_remove_offset_ratio(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def y_remove_offset_ratio(self) -> tuple[float, float]:
        ...
    @y_remove_offset_ratio.setter
    def y_remove_offset_ratio(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def z_minmax(self) -> tuple[float, float]:
        ...
    @z_minmax.setter
    def z_minmax(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def z_remove_range_ratio(self) -> tuple[float, float]:
        ...
    @z_remove_range_ratio.setter
    def z_remove_range_ratio(self, arg0: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
def create_base_range_from_json(arg0: str) -> BaseRange:
    ...
def create_machine_collision_list(file_dir: str, initial_offsets: tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], l_col_machine_conf: collections.abc.Sequence[MachineConf], reverse: tuple[bool, bool, bool] = (True, True, False)) -> list[MachineCollisionBase]:
    ...
def load_base_ranges_from_json(json_path: str) -> list[BaseRange]:
    ...
