from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['CLIFF', 'CRANE', 'CRANE_EXTERNAL_GUARD', 'CRANE_IMMOBILE', 'CRANE_IMMOBILE_FOR_DET', 'CRANE_MOBILE', 'CRANE_MOBILE_FOR_DET', 'HIGH_3D', 'HUMAN', 'LOW_3D', 'LabeledOctoNodes', 'NodeClusterKey', 'NodeEntity', 'OTHER', 'OctoNode', 'OctoTree', 'Point', 'UNK', 'VoxStats']
class LabeledOctoNodes:
    def __bool__(self) -> bool:
        """
        Check whether the map is nonempty
        """
    @typing.overload
    def __contains__(self, arg0: typing.SupportsInt | typing.SupportsIndex | str) -> bool:
        ...
    @typing.overload
    def __contains__(self, arg0: typing.Any) -> bool:
        ...
    def __delitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex | str) -> None:
        ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex | str) -> dict[tuple[int, int, int], OctoNode]:
        ...
    def __init__(self) -> None:
        ...
    def __iter__(self) -> collections.abc.Iterator[int | str]:
        ...
    def __len__(self) -> int:
        ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex | str, arg1: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], OctoNode]) -> None:
        ...
    def items(self) -> typing.ItemsView:
        ...
    def keys(self) -> typing.KeysView:
        ...
    def values(self) -> typing.ValuesView:
        ...
class NodeClusterKey:
    entity: NodeEntity
    def __eq__(self, arg0: NodeClusterKey) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __init__(self, entity: NodeEntity, cluster_id: typing.SupportsInt | typing.SupportsIndex | None = None) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def cluster_id(self) -> int | None:
        ...
    @cluster_id.setter
    def cluster_id(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
class NodeEntity:
    """
    Members:
    
      UNK
    
      HUMAN
    
      CRANE
    
      CRANE_MOBILE
    
      CRANE_IMMOBILE
    
      CRANE_MOBILE_FOR_DET
    
      CRANE_IMMOBILE_FOR_DET
    
      CRANE_EXTERNAL_GUARD
    
      CLIFF
    
      HIGH_3D
    
      LOW_3D
    
      OTHER
    """
    CLIFF: typing.ClassVar[NodeEntity]  # value = <NodeEntity.CLIFF: 9>
    CRANE: typing.ClassVar[NodeEntity]  # value = <NodeEntity.CRANE: 3>
    CRANE_EXTERNAL_GUARD: typing.ClassVar[NodeEntity]  # value = <NodeEntity.CRANE_EXTERNAL_GUARD: 8>
    CRANE_IMMOBILE: typing.ClassVar[NodeEntity]  # value = <NodeEntity.CRANE_IMMOBILE: 5>
    CRANE_IMMOBILE_FOR_DET: typing.ClassVar[NodeEntity]  # value = <NodeEntity.CRANE_IMMOBILE_FOR_DET: 7>
    CRANE_MOBILE: typing.ClassVar[NodeEntity]  # value = <NodeEntity.CRANE_MOBILE: 4>
    CRANE_MOBILE_FOR_DET: typing.ClassVar[NodeEntity]  # value = <NodeEntity.CRANE_MOBILE_FOR_DET: 6>
    HIGH_3D: typing.ClassVar[NodeEntity]  # value = <NodeEntity.HIGH_3D: 10>
    HUMAN: typing.ClassVar[NodeEntity]  # value = <NodeEntity.HUMAN: 2>
    LOW_3D: typing.ClassVar[NodeEntity]  # value = <NodeEntity.LOW_3D: 11>
    OTHER: typing.ClassVar[NodeEntity]  # value = <NodeEntity.OTHER: 12>
    UNK: typing.ClassVar[NodeEntity]  # value = <NodeEntity.UNK: 1>
    __members__: typing.ClassVar[dict[str, NodeEntity]]  # value = {'UNK': <NodeEntity.UNK: 1>, 'HUMAN': <NodeEntity.HUMAN: 2>, 'CRANE': <NodeEntity.CRANE: 3>, 'CRANE_MOBILE': <NodeEntity.CRANE_MOBILE: 4>, 'CRANE_IMMOBILE': <NodeEntity.CRANE_IMMOBILE: 5>, 'CRANE_MOBILE_FOR_DET': <NodeEntity.CRANE_MOBILE_FOR_DET: 6>, 'CRANE_IMMOBILE_FOR_DET': <NodeEntity.CRANE_IMMOBILE_FOR_DET: 7>, 'CRANE_EXTERNAL_GUARD': <NodeEntity.CRANE_EXTERNAL_GUARD: 8>, 'CLIFF': <NodeEntity.CLIFF: 9>, 'HIGH_3D': <NodeEntity.HIGH_3D: 10>, 'LOW_3D': <NodeEntity.LOW_3D: 11>, 'OTHER': <NodeEntity.OTHER: 12>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class OctoNode:
    __hash__: typing.ClassVar[None] = None
    entity: NodeEntity
    node_stats: VoxStats
    @staticmethod
    def morton_decode_3d(morton_code: typing.SupportsInt | typing.SupportsIndex) -> tuple[int, int, int]:
        ...
    @staticmethod
    def morton_encode_3d(x: typing.SupportsInt | typing.SupportsIndex, y: typing.SupportsInt | typing.SupportsIndex, z: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def __eq__(self, arg0: OctoNode) -> bool:
        ...
    def __init__(self, vox_coord: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], entity: NodeEntity = NodeEntity.UNK, node_stats: VoxStats = None) -> None:
        ...
    def __ne__(self, arg0: OctoNode) -> bool:
        ...
    def __str__(self) -> str:
        ...
    def free_vox_stats(self) -> None:
        ...
    def get_cluster_label(self) -> int | None:
        ...
    def get_far_point(self) -> tuple[float, float, float] | None:
        ...
    def get_mean(self) -> tuple[float, float, float] | None:
        ...
    def get_near_point(self) -> tuple[float, float, float] | None:
        ...
    def get_quantile(self) -> tuple[float, float, float] | None:
        ...
    def set_cluster_label(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def cluster_label(self) -> int | None:
        ...
    @cluster_label.setter
    def cluster_label(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
    @property
    def morton_code(self) -> int:
        ...
    @morton_code.setter
    def morton_code(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class OctoTree:
    MACHINE_DETECT_LABEL: typing.ClassVar[str] = 'machine_detect'
    MACHINE_MEASURE_LABEL: typing.ClassVar[str] = 'machine_measure'
    labeled_octo_nodes: argus_synchro_lib.octotree.LabeledOctoNodes | None
    use_node_stats: bool
    @staticmethod
    def get_cuboid_boundary(min_x: typing.SupportsInt | typing.SupportsIndex, min_y: typing.SupportsInt | typing.SupportsIndex, min_z: typing.SupportsInt | typing.SupportsIndex, max_x: typing.SupportsInt | typing.SupportsIndex, max_y: typing.SupportsInt | typing.SupportsIndex, max_z: typing.SupportsInt | typing.SupportsIndex, step: typing.SupportsInt | typing.SupportsIndex = 2) -> set[tuple[int, int, int]]:
        ...
    @staticmethod
    def limit_pcd_range(pcd_data: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], min_data: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"], max_data: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    def __init__(self, xyz: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"] | None = None, max_xyz: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., min_xyz: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., max_tree_depth: typing.SupportsFloat | typing.SupportsIndex = 7, xyz_entity: NodeEntity = NodeEntity.UNK, use_node_stats: bool = False, quantile: typing.SupportsFloat | typing.SupportsIndex | None = None, origin_w2oct: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] | None = None) -> None:
        ...
    def calc_vox_quantile(self, vox_xyz: typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]", "flags.f_contiguous"], w_xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], quantile: typing.SupportsFloat | typing.SupportsIndex) -> dict[tuple[int, int, int], tuple[float, float, float]]:
        ...
    def calc_vox_statistics(self, vox_xyz: typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]", "flags.f_contiguous"], w_xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> dict[tuple[int, int, int], VoxStats]:
        ...
    def create_octonodes(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], entity: NodeEntity = NodeEntity.UNK, removed_vox_min_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]] | None = None, removed_vox_max_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]] | None = None, remove_dist: typing.SupportsInt | typing.SupportsIndex = 1) -> OctoTree:
        ...
    def erase_nodes_for_entities(self, entities: collections.abc.Sequence[NodeEntity]) -> list[dict[tuple[int, int, int], OctoNode] | list[tuple[tuple[int, int, int], OctoNode]]]:
        ...
    def erase_nodes_for_entities_noret(self, entities: collections.abc.Sequence[NodeEntity]) -> None:
        ...
    def get_clustering_data_by_entity(self, cluster_entity: NodeEntity, cluster_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def get_np_from_entity_octonodes_by_chunk(self, target_entities: collections.abc.Sequence[NodeEntity], tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def get_np_from_entity_octonodes_by_list(self, target_entities: collections.abc.Sequence[NodeEntity], tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]]:
        ...
    def get_octonodes_np_coord_entity(self, target_entities: collections.abc.Sequence[NodeEntity], tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def get_octonodes_np_coord_labeled(self, target_labels: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = None, tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def get_octonodes_np_coord_labeled_v2(self, target_labels: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = None, tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def get_octonodes_np_coord_unlabeled(self, tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def get_octonodes_oct_coord_unlabeled(self, tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def get_octonodes_vox_coord_unlabled(self, tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"]:
        ...
    def get_vox_from_entity_octonodes_by_chunk(self, target_entities: collections.abc.Sequence[NodeEntity], tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"]:
        ...
    def insert_clustering_result(self, clustered_data: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], labels: typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]) -> OctoTree:
        ...
    def insert_clustering_result_v2(self, clustered_data: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], labels: typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]) -> OctoTree:
        ...
    def insert_entity_result(self, cluster2entity: collections.abc.Mapping[typing.SupportsInt | typing.SupportsIndex, NodeEntity]) -> OctoTree:
        ...
    def insert_entity_result_v2(self, cluster2entity: collections.abc.Mapping[typing.SupportsInt | typing.SupportsIndex, NodeEntity]) -> OctoTree:
        ...
    def insert_labeles_and_move_in_octonodes(self, clustered_data: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], labels: typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]", "flags.f_contiguous"], cluster_entity: NodeEntity) -> OctoTree:
        ...
    def insert_or_create_octonodes(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], entity: NodeEntity = NodeEntity.UNK, removed_vox_min_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]] | None = None, removed_vox_max_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]] | None = None, remove_dist: typing.SupportsInt | typing.SupportsIndex = 1) -> OctoTree:
        ...
    def insert_or_entity_octonodes(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], entity: NodeEntity = NodeEntity.OTHER, entity_replace: bool = False, is_order: bool = False, removed_vox_min_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]] | None = None, removed_vox_max_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]] | None = None, remove_dist: typing.SupportsInt | typing.SupportsIndex = 1) -> OctoTree:
        ...
    def insert_or_entity_octonodes_with_labels(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], labels: typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], entity: NodeEntity = NodeEntity.CLIFF, entity_replace: bool = False, is_order: bool = True, removed_vox_min_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]] | None = None, removed_vox_max_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]] | None = None, remove_dist: typing.SupportsInt | typing.SupportsIndex = 1) -> OctoTree:
        ...
    def oct2vox_coords(self, oct_coords: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None, remove_dep: bool = True) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"]:
        ...
    def oct2w_coords(self, oct_coords: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def replace_entities_in_octonodes(self, from_entity: NodeEntity, cluster_transfered_entity: collections.abc.Mapping[typing.SupportsInt | typing.SupportsIndex | None, NodeEntity]) -> OctoTree:
        ...
    def vox2oct_coords(self, vox_coords: typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]", "flags.f_contiguous"], tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def vox2w_coords(self, vox_coords: typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]", "flags.f_contiguous"], tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def w2oct_coords(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def w2vox_coords(self, xyz: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], tree_depth: typing.SupportsInt | typing.SupportsIndex | None = None, remove_dep: bool = True) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"]:
        ...
    @property
    def cell_interval(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @cell_interval.setter
    def cell_interval(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @property
    def cluster_vox2deepest_vox(self) -> dict[tuple[int, int, int], list[tuple[int, int, int]]]:
        ...
    @cluster_vox2deepest_vox.setter
    def cluster_vox2deepest_vox(self, arg0: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]]]) -> None:
        ...
    @property
    def entity_octonodes(self) -> dict[NodeClusterKey, dict[tuple[int, int, int], OctoNode] | list[tuple[tuple[int, int, int], OctoNode]]]:
        ...
    @entity_octonodes.setter
    def entity_octonodes(self, arg0: collections.abc.Mapping[NodeClusterKey, collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], OctoNode] | collections.abc.Sequence[tuple[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], OctoNode]]]) -> None:
        ...
    @property
    def max_tree_depth(self) -> int:
        ...
    @max_tree_depth.setter
    def max_tree_depth(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def max_xyz(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @max_xyz.setter
    def max_xyz(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @property
    def min_xyz(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @min_xyz.setter
    def min_xyz(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @property
    def origin_w2oct(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"] | None:
        ...
    @origin_w2oct.setter
    def origin_w2oct(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] | None) -> None:
        ...
    @property
    def quantile(self) -> float | None:
        ...
    @quantile.setter
    def quantile(self, arg0: typing.SupportsFloat | typing.SupportsIndex | None) -> None:
        ...
    @property
    def unlabeled_octo_nodes(self) -> dict[tuple[int, int, int], OctoNode] | None:
        ...
    @unlabeled_octo_nodes.setter
    def unlabeled_octo_nodes(self, arg0: collections.abc.Mapping[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], OctoNode] | None) -> None:
        ...
class Point:
    is_null: bool
    def __init__(self) -> None:
        ...
    @property
    def x(self) -> float:
        ...
    @x.setter
    def x(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def y(self) -> float:
        ...
    @y.setter
    def y(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def z(self) -> float:
        ...
    @z.setter
    def z(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class VoxStats:
    far_point: Point
    first_moment: Point
    near_point: Point
    quantile: Point
    second_moment: Point
    def __init__(self) -> None:
        ...
    @property
    def counts(self) -> int:
        ...
    @counts.setter
    def counts(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def far_dist(self) -> float:
        ...
    @far_dist.setter
    def far_dist(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def near_dist(self) -> float:
        ...
    @near_dist.setter
    def near_dist(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
CLIFF: NodeEntity  # value = <NodeEntity.CLIFF: 9>
CRANE: NodeEntity  # value = <NodeEntity.CRANE: 3>
CRANE_EXTERNAL_GUARD: NodeEntity  # value = <NodeEntity.CRANE_EXTERNAL_GUARD: 8>
CRANE_IMMOBILE: NodeEntity  # value = <NodeEntity.CRANE_IMMOBILE: 5>
CRANE_IMMOBILE_FOR_DET: NodeEntity  # value = <NodeEntity.CRANE_IMMOBILE_FOR_DET: 7>
CRANE_MOBILE: NodeEntity  # value = <NodeEntity.CRANE_MOBILE: 4>
CRANE_MOBILE_FOR_DET: NodeEntity  # value = <NodeEntity.CRANE_MOBILE_FOR_DET: 6>
HIGH_3D: NodeEntity  # value = <NodeEntity.HIGH_3D: 10>
HUMAN: NodeEntity  # value = <NodeEntity.HUMAN: 2>
LOW_3D: NodeEntity  # value = <NodeEntity.LOW_3D: 11>
OTHER: NodeEntity  # value = <NodeEntity.OTHER: 12>
UNK: NodeEntity  # value = <NodeEntity.UNK: 1>
