from __future__ import annotations
import argus_synchro_lib.dataclass
import argus_synchro_lib.octotree
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['Scene', 'SceneDescriptionConf']
class Scene:
    def __getstate__(self) -> dict[str, typing.Any]:
        ...
    def __init__(self, scene_conf: SceneDescriptionConf, logfunc: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex, str], None]) -> None:
        ...
    def __setstate__(self, arg0: dict[str, typing.Any]) -> None:
        ...
    def aggregate2d3d_results(self, camera_cluster2entities: collections.abc.Sequence[collections.abc.Mapping[typing.SupportsInt | typing.SupportsIndex | None, argus_synchro_lib.octotree.NodeEntity]], octotree_obj: argus_synchro_lib.octotree.OctoTree, from_entity: argus_synchro_lib.octotree.NodeEntity = argus_synchro_lib.octotree.NodeEntity.OTHER) -> tuple[argus_synchro_lib.octotree.OctoTree, dict[int | None, argus_synchro_lib.octotree.NodeEntity]]:
        ...
    def append_distance_info(self, collision_clusters: collections.abc.Mapping[typing.SupportsInt | typing.SupportsIndex | None, tuple[argus_synchro_lib.octotree.OctoNode, argus_synchro_lib.octotree.OctoNode, tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], typing.SupportsFloat | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex | None]], minmax: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"], origin: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ...) -> dict[int | None, tuple[argus_synchro_lib.octotree.OctoNode, argus_synchro_lib.octotree.OctoNode, tuple[float, float, float], tuple[float, float, float], float, float | None]]:
        ...
    def integrate2d3d(self, camera: argus_synchro_lib.dataclass.Camera, bb_box_data: argus_synchro_lib.dataclass.CameraDetectionData, boxes: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], minmax: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"], valid_detects: typing.SupportsInt | typing.SupportsIndex, from_entity: argus_synchro_lib.octotree.NodeEntity = argus_synchro_lib.octotree.NodeEntity.OTHER, method: str = 'center') -> dict[int | None, argus_synchro_lib.octotree.NodeEntity]:
        ...
    def update(self, scene_conf: SceneDescriptionConf, logfunc: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex, str], None]) -> None:
        ...
class SceneDescriptionConf:
    use_human_gate: bool
    def __getstate__(self) -> dict[str, typing.Any]:
        ...
    def __init__(self) -> None:
        ...
    def __setstate__(self, arg0: dict[str, typing.Any]) -> None:
        ...
    @property
    def D_max(self) -> float:
        ...
    @D_max.setter
    def D_max(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def D_min(self) -> float:
        ...
    @D_min.setter
    def D_min(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def H_max(self) -> float:
        ...
    @H_max.setter
    def H_max(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def H_min(self) -> float:
        ...
    @H_min.setter
    def H_min(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def W_max(self) -> float:
        ...
    @W_max.setter
    def W_max(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def W_min(self) -> float:
        ...
    @W_min.setter
    def W_min(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def coarse_hi(self) -> float:
        ...
    @coarse_hi.setter
    def coarse_hi(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def coarse_lo(self) -> float:
        ...
    @coarse_lo.setter
    def coarse_lo(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def final_threshold(self) -> float:
        ...
    @final_threshold.setter
    def final_threshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def h_ref_px(self) -> int:
        ...
    @h_ref_px.setter
    def h_ref_px(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def hi_ceil(self) -> float:
        ...
    @hi_ceil.setter
    def hi_ceil(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def hi_gain(self) -> float:
        ...
    @hi_gain.setter
    def hi_gain(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def k_min(self) -> float:
        ...
    @k_min.setter
    def k_min(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def lo_floor(self) -> float:
        ...
    @lo_floor.setter
    def lo_floor(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def lo_gain(self) -> float:
        ...
    @lo_gain.setter
    def lo_gain(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def tall_ratio_min(self) -> float:
        ...
    @tall_ratio_min.setter
    def tall_ratio_min(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def vertical_w_iou(self) -> float:
        ...
    @vertical_w_iou.setter
    def vertical_w_iou(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def vertical_w_phi(self) -> float:
        ...
    @vertical_w_phi.setter
    def vertical_w_phi(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def vertical_w_scale(self) -> float:
        ...
    @vertical_w_scale.setter
    def vertical_w_scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
