"""
pybind11 bindings for spsc_slot_controller
"""
from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['SpscSlotController']
class SpscSlotController:
    def __init__(self, state: typing.Annotated[numpy.typing.ArrayLike, numpy.int64], slot_count: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def acquire_read_slot_latest(self, last_seq: typing.SupportsInt | typing.SupportsIndex) -> tuple[int, int]:
        ...
    def acquire_read_slot_sync(self) -> tuple[int, int]:
        ...
    def publish(self, slot: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def published_seq(self) -> int:
        ...
    def release_read_slot(self, slot: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def reserve_write_slot_latest(self) -> int:
        ...
    def reserve_write_slot_sync(self) -> int:
        ...
