"""
pybind11 bindings for UI_interface and UIIFConf
"""
from __future__ import annotations
import argus_synchro_lib.octotree
import collections.abc
import typing
__all__: list[str] = ['CLIFF_LEVEL', 'GeneralConf', 'UIIFConf', 'UI_interface']
class CLIFF_LEVEL:
    """
    Members:
    
      NORMAL
    
      ATTENTION
    
      WARNING
    """
    ATTENTION: typing.ClassVar[CLIFF_LEVEL]  # value = <CLIFF_LEVEL.ATTENTION: 1>
    NORMAL: typing.ClassVar[CLIFF_LEVEL]  # value = <CLIFF_LEVEL.NORMAL: 0>
    WARNING: typing.ClassVar[CLIFF_LEVEL]  # value = <CLIFF_LEVEL.WARNING: 2>
    __members__: typing.ClassVar[dict[str, CLIFF_LEVEL]]  # value = {'NORMAL': <CLIFF_LEVEL.NORMAL: 0>, 'ATTENTION': <CLIFF_LEVEL.ATTENTION: 1>, 'WARNING': <CLIFF_LEVEL.WARNING: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class GeneralConf:
    def __init__(self, in_factory: bool, operation_mode: typing.SupportsInt | typing.SupportsIndex, has_external_guard: bool, external_guard_offset: typing.SupportsFloat | typing.SupportsIndex, ground_height: typing.SupportsFloat | typing.SupportsIndex, ground_height_margin: typing.SupportsFloat | typing.SupportsIndex, rotation_radius: typing.SupportsFloat | typing.SupportsIndex, initial_transform_file: str) -> None:
        ...
    @property
    def external_guard_offset(self) -> float:
        ...
    @property
    def ground_height(self) -> float:
        ...
    @property
    def ground_height_margin(self) -> float:
        ...
    @property
    def has_external_guard(self) -> bool:
        ...
    @property
    def in_factory(self) -> bool:
        ...
    @property
    def initial_transform_file(self) -> str:
        ...
    @property
    def operation_mode(self) -> int:
        ...
    @property
    def rotation_radius(self) -> float:
        ...
class UIIFConf:
    damp_out: bool
    draw_bbox_3d: bool
    draw_collision: bool
    show_unk: bool
    def __init__(self, damp_out: bool, bbox_3d_num: typing.SupportsInt | typing.SupportsIndex, bbox_3d_distance: typing.SupportsFloat | typing.SupportsIndex, UI_mmap: collections.abc.Sequence[str], damp_mmap: collections.abc.Sequence[str], show_unk: bool, collision_depict_dist: typing.SupportsFloat | typing.SupportsIndex, collision_attention_dist: typing.SupportsFloat | typing.SupportsIndex, collision_warning_dist: typing.SupportsFloat | typing.SupportsIndex, cliff_attention_dist: typing.SupportsFloat | typing.SupportsIndex, cliff_warning_dist: typing.SupportsFloat | typing.SupportsIndex, draw_bbox_3d: bool, draw_collision: bool) -> None:
        ...
    @property
    def UI_mmap(self) -> list[str]:
        ...
    @UI_mmap.setter
    def UI_mmap(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def bbox_3d_distance(self) -> float:
        ...
    @bbox_3d_distance.setter
    def bbox_3d_distance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def bbox_3d_num(self) -> int:
        ...
    @bbox_3d_num.setter
    def bbox_3d_num(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def cliff_attention_dist(self) -> float:
        ...
    @cliff_attention_dist.setter
    def cliff_attention_dist(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def cliff_warning_dist(self) -> float:
        ...
    @cliff_warning_dist.setter
    def cliff_warning_dist(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def collision_attention_dist(self) -> float:
        ...
    @collision_attention_dist.setter
    def collision_attention_dist(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def collision_depict_dist(self) -> float:
        ...
    @collision_depict_dist.setter
    def collision_depict_dist(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def collision_warning_dist(self) -> float:
        ...
    @collision_warning_dist.setter
    def collision_warning_dist(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def damp_mmap(self) -> list[str]:
        ...
    @damp_mmap.setter
    def damp_mmap(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
class UI_interface:
    def __init__(self, ui_if: UIIFConf, s_frame: typing.SupportsInt | typing.SupportsIndex, rotation_radius: typing.SupportsFloat | typing.SupportsIndex, camera_num: typing.SupportsInt | typing.SupportsIndex, has_external_guard: bool, external_guard_offset: typing.SupportsFloat | typing.SupportsIndex, status_mmap_path: str, logfunc: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex, str], None]) -> None:
        ...
    def cliff_info(self) -> None:
        ...
    def collision_info(self) -> None:
        ...
    def damp_info(self) -> None:
        ...
    def machine_info(self, angle_deg: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def postprocess_info(self, ret_t: typing.SupportsInt | typing.SupportsIndex, process_time_ms: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def preprocess_info(self) -> None:
        ...
    def set_cliff_info_by_octreee(self, octotree_obj: argus_synchro_lib.octotree.OctoTree) -> None:
        ...
    def zero_padding(self, n_byte: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
