from __future__ import annotations
import numpy
import typing
__all__: list[str] = ['iou_3d_cpu', 'iou_bev_cpu', 'subsample', 'subsample_batch']
def iou_3d_cpu(boxes_a: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]], boxes_b: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]]) -> numpy.ndarray[typing.Any, numpy.dtype[typing.Any]]:
    ...
def iou_bev_cpu(boxes_a: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]], boxes_b: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]]) -> numpy.ndarray[typing.Any, numpy.dtype[typing.Any]]:
    ...
def subsample(points: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]], features: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]] | None = None, classes: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]] | None = None, sampleDl: float = 0.1, verbose: int = 0) -> typing.Any:
    ...
def subsample_batch(points: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]], batches: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]], features: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]] | None = None, classes: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]] | None = None, sampleDl: float = 0.1, method: str = 'barycenters', max_p: int = 0, verbose: int = 0) -> tuple:
    ...
