[DEFAULT]
# ルートディレクトリ: config_dir / log_dir / mmap_dir は CLI引数で上書きされる。
config_dir = /opt/argus3d/config/core
log_dir = /var/log/argus3d
#log_dir = /media/shiuser/ボリューム/X6T304
mmap_dir = /dev/shm
home_dir = ./
file_input = True
# data_dir = /mnt/nvme/
data_dir = /mnt/nvme
outputdir_root = ${DEFAULT:log_dir}/tmpCalib
print_disabled = True

[debug]
save_cornerlist_pickle = False
is_enable_profiler = False
enable_debugdata_store = False

#2D-3D校正自動精度評価: autoexit=Trueにした上でsettings.ini側校正モード1、2D3D校正True、校正リクエストフラグFalseに設定
#   (誤設定防止用に、このコンディションを満たさなければ例外で落とすようにしてあります。)
calib2d3d_fileend_autoexit = False
calib2d3d_fileend_autoexit_flagfile_path = ${DEFAULT:config_dir}/calibration_mat_generator_modules/temp/calib2d3d_fileend_autoexit.tmp

[DEBUG_REF]
# lidarx_file_camy: DataCapture_Lidarセクションから参照 x:撮影したカメラ・センサ y:どのカメラ校正向けのデータか
# vx_file_camy: DataCapture_Cameraセクションから参照
# lidarxcalib_for_camy: DataConverter2D3D_Lidarセクションから参照

#データパス（読み込み先変更時）
# 左用 実際のファイルパス (lidarx_file_camyはファイル名6ケタ数値前のパス・プレフィクス) 
lidar0calib_for_cam0 = ${lidar0_O2502004}
lidar1calib_for_cam0 = ${lidar1_O2502004}

# リア用 実際のファイルパス (同上）
lidar0calib_for_cam1 = ${lidar0_O2502029}
lidar1calib_for_cam1 = ${lidar1_O2502029}

# 右用 実際のファイルパス (同上）
lidar0calib_for_cam2 = ${lidar0_O2502004}
lidar1calib_for_cam2 = ${lidar1_O2502004}

# 読込ファイルパス

#データパス（読み込み先変更時）
# 標準状態　左 
lidar0_file_cam0 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convpoint/cap_0203_cam120250203_141106ts.csv/L/Lpoint_
lidar1_file_cam0 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convpoint/cap_0203_cam120250203_141106ts.csv/R/Rpoint_

# 標準状態　リア
lidar0_file_cam1 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convpoint/cap_0203_cam120250203_170738ts.csv/L/Lpoint_
lidar1_file_cam1 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convpoint/cap_0203_cam120250203_170738ts.csv/R/Rpoint_

# 標準状態　右 
lidar0_file_cam2 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convpoint/cap_0203_cam120250203_141855ts.csv/L/Lpoint_
lidar1_file_cam2 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convpoint/cap_0203_cam120250203_141855ts.csv/R/Rpoint_

v0_file_cam0 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convvideo_can10fpssync/cam0_20250203_141105_10fps.mp4
v1_file_cam0 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convvideo_can10fpssync/cam1_20250203_141106_10fps.mp4
v2_file_cam0 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convvideo_can10fpssync/cam2_20250203_141106_10fps.mp4

v0_file_cam1 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convvideo_can10fpssync/cam0_20250203_170738_10fps.mp4
v1_file_cam1 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convvideo_can10fpssync/cam1_20250203_170738_10fps.mp4
v2_file_cam1 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convvideo_can10fpssync/cam2_20250203_170738_10fps.mp4

v0_file_cam2 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convvideo_can10fpssync/cam0_20250203_141855_10fps.mp4
v1_file_cam2 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convvideo_can10fpssync/cam1_20250203_141855_10fps.mp4
v2_file_cam2 = ${DEFAULT:data_dir}/experiment2025/ohbu20250203_0204/convvideo_can10fpssync/cam2_20250203_141856_10fps.mp4

lidar0_O2502029 = ${DEFAULT:data_dir}/experiment2025/lidar_calibration_params/O2502029/transformation_matrix_left.csv
lidar1_O2502029 = ${DEFAULT:data_dir}/experiment2025/lidar_calibration_params/O2502029/transformation_matrix_right.csv
lidar0_O2502004 = ${DEFAULT:data_dir}/experiment2025/lidar_calibration_params/O2502004/transformation_matrix_left.csv
lidar1_O2502004 = ${DEFAULT:data_dir}/experiment2025/lidar_calibration_params/O2502004/transformation_matrix_right.csv

lidar0_ohbu20251127best = ${DEFAULT:config_dir}/calibration_mat_generator_modules/20251127ohbucalibdata/lidar2crane_trans_mat_0.csv
lidar1_ohbu20251127best = ${DEFAULT:config_dir}/calibration_mat_generator_modules/20251127ohbucalibdata/lidar2crane_trans_mat_1.csv
camera0_ohbu20251127best = ${DEFAULT:config_dir}/calibration_mat_generator_modules/20251127ohbucalibdata/camera0transmat.csv
camera1_ohbu20251127best = ${DEFAULT:config_dir}/calibration_mat_generator_modules/20251127ohbucalibdata/camera1transmat.csv
camera2_ohbu20251127best = ${DEFAULT:config_dir}/calibration_mat_generator_modules/20251127ohbucalibdata/camera2transmat.csv

Scruit3d3dmat_lid0 = ./calibration/3d-3d/lidar2crane_trans_mat_0.csv
Scruit3d3dmat_lid1 = ./calibration/3d-3d/lidar2crane_trans_mat_1.csv

lidar0_calib_replace = ${DEFAULT:data_dir}/experiment2025/lidar_calibration_params/O2502040/transformation_matrix_left.csv
lidar1_calib_replace = ${DEFAULT:data_dir}/experiment2025/lidar_calibration_params/O2502040/transformation_matrix_right.csv

# ---- ここまで ----

[Filepath_IO]
# 校正要否確認で使う3D3D校正ファイル
CalibCheck3d3dmat_lid0 = ./calibration/3d-3d/lidar2crane_trans_mat_0.csv
CalibCheck3d3dmat_lid1 = ./calibration/3d-3d/lidar2crane_trans_mat_1.csv

# 校正要否確認の対象となる校正ファイル（左辺変更禁止）
CalibCheck2d3dmat_cam0 = ./calibration/2d-3d/camera0transmat.csv
CalibCheck2d3dmat_cam1 = ./calibration/2d-3d/camera1transmat.csv
CalibCheck2d3dmat_cam2 = ./calibration/2d-3d/camera2transmat.csv


# 校正要否確認出力先（テキストでOK/NG/UNKNOWNを出力）
resultfiles_camera0 = ${DEFAULT:outputdir_root}/calibcheck2d3d_results_camera0.txt
resultfiles_camera1 = ${DEFAULT:outputdir_root}/calibcheck2d3d_results_camera1.txt
resultfiles_camera2 = ${DEFAULT:outputdir_root}/calibcheck2d3d_results_camera2.txt

#校正結果出力先（左辺変更禁止）
#本番用
Calib3d3dmat_lid0 = ${DEFAULT:outputdir_root}/3d-3d/lidar2crane_trans_mat_0.csv
Calib3d3dmat_lid1 = ${DEFAULT:outputdir_root}/3d-3d/lidar2crane_trans_mat_1.csv
Calib2d3dmat_cam0 = ${DEFAULT:outputdir_root}/2d-3d/camera0transmat.csv
Calib2d3dmat_cam1 = ${DEFAULT:outputdir_root}/2d-3d/camera1transmat.csv
Calib2d3dmat_cam2 = ${DEFAULT:outputdir_root}/2d-3d/camera2transmat.csv

#デバッグ用(校正行列受け渡し用のディレクトリに書き込まない)
#Calib3d3dmat_lid0 = lidar2crane_trans_mat_0_debug.csv
#Calib3d3dmat_lid1 = lidar2crane_trans_mat_1_debug.csv
#Calib2d3dmat_cam0 = camera0transmat_debug.csv
#Calib2d3dmat_cam1 = camera1transmat_debug.csv
#Calib2d3dmat_cam2 = camera2transmat_debug.csv

#プログラム読込項目（変更禁止）
Calib3d3dmat_lidars = [${Filepath_IO:Calib3d3dmat_lid0},${Filepath_IO:Calib3d3dmat_lid1}]
Calib2d3dmat_cameras = [${Filepath_IO:Calib2d3dmat_cam0},${Filepath_IO:Calib2d3dmat_cam1},${Filepath_IO:Calib2d3dmat_cam2}]


[General]
initial_transform_file = ./calibration/3d-3d/lidar_initial_pose_SCX9003.csv

[DataCapture]
s_frame = 1
e_frame = 5000000
sync_type = ByTime_Nearby
#sync_type = ByIndex
datawait_sec = 5
save_sensordata = False
save_sensordata_dir = /media/shiuser/ssd_manualmnt/matsunaga/20251120
#save_sensordata_dir = ${DEFAULT:outputdir_root}

[DataCapture_Lidar]
count = 2
#センサライブラリ使用時
path = ${DEFAULT:config_dir}/config_lidars.json
config_file = ${DEFAULT:config_dir}/lidar.json
accum_time = 0.1
dev_str = mid360
data_buffersize = 50
framethinning_bufferlen_threshold = 25

#ファイル読み込みモード
#lidar_files = ${DEBUG_REF:lidar_files}
lidar_files_for_cam0calib=[${DEBUG_REF:lidar0_file_cam0},${DEBUG_REF:lidar1_file_cam0}]
lidar_files_for_cam1calib=[${DEBUG_REF:lidar0_file_cam1},${DEBUG_REF:lidar1_file_cam1}]
lidar_files_for_cam2calib=[${DEBUG_REF:lidar0_file_cam2},${DEBUG_REF:lidar1_file_cam2}]
# 2D3D校正以外: cam1用を入れておく
lidar_files_for_othermode=[${DEBUG_REF:lidar0_file_cam1},${DEBUG_REF:lidar1_file_cam1}]

allow_lack = True
capture_latency_ms = 10
lidarfile_basetime = 2025-09-01_09-00-00
lidarfile_steptime = 0.1
#各LiDAR個別の取得範囲制限
capturerange_x_max = 30
capturerange_x_min = -30
capturerange_y_max = 30
capturerange_y_min = -30
capturerange_z_max = 30
capturerange_z_min = -30

[DataCapture_Camera]
count = 3
config_file = ${DEFAULT:config_dir}/camera_three.json
#カメラ入力画像サイズ(不要では？)
video_width = 1280
video_height = 720
#システム使用画像サイズ（変換行列計算に必要）
sys_width = 1920
sys_height = 1080
data_buffersize = 50
framethinning_bufferlen_threshold = 25
capture_latency_ms = 10

#video_files = ${DEBUG_REF:video_files}
video_files_for_cam0calib= [${DEBUG_REF:v0_file_cam0},${DEBUG_REF:v1_file_cam0},${DEBUG_REF:v2_file_cam0}]
video_files_for_cam1calib= [${DEBUG_REF:v0_file_cam1},${DEBUG_REF:v1_file_cam1},${DEBUG_REF:v2_file_cam1}]
video_files_for_cam2calib= [${DEBUG_REF:v0_file_cam2},${DEBUG_REF:v1_file_cam2},${DEBUG_REF:v2_file_cam2}]
#cam1向けを入れておく
video_files_for_othermode= [${DEBUG_REF:v0_file_cam1},${DEBUG_REF:v1_file_cam1},${DEBUG_REF:v2_file_cam1}]

#タイムスタンプベース：日時タイムスタンプでの同期を取っているためファイル入力時は失われたタイムスタンプにダミー値を追加する必要がある
videofile_basetime = 2025-09-01_09-00-00
videofile_steptime = 0.1

#for realtime
motec = True
porttable = [10750,10780,10770]
iptable = [192.168.1.75,192.168.1.78,192.168.1.77]
framerate_div = 3

[DataConverter2D3D_Camera]
undistort_enable = True
intrinsics_path = ./calibration/camera_intrinsics_MCDE7180A.json

[DataConverter2D3D_Lidar]
calib_lidar2crane = True
bothlidars = ./calibration/3d-3d/lidar2lidar_trans_mat_MID360.csv
calibration_coord_rtvec_jsonpath = ${DEFAULT:config_dir}/calibration_mat_generator_modules/calibration_coordinate_convert_rtvec_scx900.json

#lidar_calib_files = ${DEBUG_REF:lidar_calib_files}
lidar_calib_files_for_cam0calib = [${DEBUG_REF:lidar0calib_for_cam0},${DEBUG_REF:lidar1calib_for_cam0}]
lidar_calib_files_for_cam1calib = [${DEBUG_REF:lidar0calib_for_cam1},${DEBUG_REF:lidar1calib_for_cam1}]
lidar_calib_files_for_cam2calib = [${DEBUG_REF:lidar0calib_for_cam2},${DEBUG_REF:lidar1calib_for_cam2}]
# 2D3D校正以外はcam1向けデータを流す
lidar_calib_files_for_othermode = [${DEBUG_REF:lidar0calib_for_cam1},${DEBUG_REF:lidar1calib_for_cam1}]

sensors = 2
voxel_down_sample_voxelsize = 0.05
voxel_down_sample_enable_afteraccum = True
accumulate_length = 3

[Calib2d3d_General]
placeholder = 

[Calib2d3d_Proc2d]
intrinsics_path = ./calibration/camera_intrinsics_MCDE7180A.json
yolo_obj_countlimit = 50
yolo_type = DAMO-YOLO
#yolo_modelpath = ./checkpoints/damoyolo_tinynasL45_L_3.onnx
yolo_modelpath = ./checkpoints/damoyolo_large.onnx
conf_thresh = 0.5
nms_thresh = 0.45
camera_mask_images = [${DEFAULT:config_dir}/calibration_mat_generator_modules/camera_mask.png,${DEFAULT:config_dir}/calibration_mat_generator_modules/camera_mask.png,${DEFAULT:config_dir}/calibration_mat_generator_modules/camera_mask.png]
enable_bboxfilter_byimg = False
enable_edgebboxfilter = True
enable_imgmask = False
enable_bbox_shapefilter = False
enable_bbox2D_shapefilter = False
yolothreshold = 0.5
bbox_tracking_framelen_min = 50
bbox_tracking_movelen_pixels = 300
bbox_tracking_workarea2d_count = 20

lost_track_buffer = 30
tracking_frame_rate = 10.0
track_activation_threshold = 0.25
minimum_consecutive_frames = 3
minimum_iou_threshold = 0.3

cam_valmat_path = [${DEFAULT:config_dir}/calibration_mat_generator_modules/image_evaluation_value_FHD_origin960-923.npy,${DEFAULT:config_dir}/calibration_mat_generator_modules/image_evaluation_value_FHD_origin960-923.npy,${DEFAULT:config_dir}/calibration_mat_generator_modules/image_evaluation_value_FHD_origin960-923.npy]
# 設定値：入力座標(x_i,y_i) -> 参照座標(x_r,y_r) への一次変換係数
cam_valmat_coord_A_X = [1,1,1]
cam_valmat_coord_B_X = [0,0,0]
cam_valmat_coord_A_Y = [1,1,1]
cam_valmat_coord_B_Y = [0,0,0]

# 設定値4：デフォルト値（範囲外参照時に返す）
cam_valmat_val_DEFAULT = [10000,10000,10000]

# 座標に対する作業エリア定義mat（白黒画像）のパス
cam_workareadef_img_path = [${DEFAULT:config_dir}/calibration_mat_generator_modules/image_workarea_def.png,${DEFAULT:config_dir}/calibration_mat_generator_modules/image_workarea_def.png,${DEFAULT:config_dir}/calibration_mat_generator_modules/image_workarea_def.png]
# 設定値：入力座標(x_i,y_i) -> 参照座標(x_r,y_r) への一次変換係数
cam_workareadef_img_coord_A_X = [1,1,1]
cam_workareadef_img_coord_B_X = [0,0,0]
cam_workareadef_img_coord_A_Y = [1,1,1]
cam_workareadef_img_coord_B_Y = [0,0,0]
cam_workareadef_img_coord_A_ETA = [1,1,1]
cam_workareadef_img_coord_B_ETA = [0,0,0]
# 設定値4：デフォルト値（範囲外参照時に返す）
cam_workareadef_img_val_DEFAULT = [0,0,0]

[Calib2d3d_Proc3d]
datarange_x_min = -15
datarange_x_max = 15
datarange_y_min = 0
datarange_y_max = 10
datarange_z_min = -0.88
datarange_z_max = 10
dbscan_eps = 0.5
dbscan_min_samples = 10
groundplane_ransac_coeff = 0.4
groundplane_ptthinning_div = 10
gplane_detection_walkingarea_limit = True
groundplane_requiredpoints = 30000
save_debugdata = False
enable_static_point_filter = True
static_point_filter_boxelsize = 1.0
static_point_filter_initlength = 6
static_point_filter_refresh_period = 100

bbox_tracking_framelen_min = 50
bbox_tracking_movelen_meters = 5.0
bbox_tracking_workarea3d_count = 20

lost_track_buffer = 60
tracking_frame_rate = 10.0
track_activation_threshold = 0.25
minimum_consecutive_frames = 10
minimum_iou_threshold = 0.001

is_headpoint_overwrite = True
calc_headpoint_pointrange_x_min = -10.0
calc_headpoint_pointrange_x_max = 10.0
calc_headpoint_pointrange_y_min = 3.0
calc_headpoint_pointrange_y_max = 10.0

is_footpoints_fixed = True
footpoints_zval = -1.36

# 座標に対する評価値のパス
lid_valmat_path = [${DEFAULT:config_dir}/calibration_mat_generator_modules/pcd_evaluation_value_20m10m_origin0.npy,${DEFAULT:config_dir}/calibration_mat_generator_modules/pcd_evaluation_value_20m10m_origin0.npy,${DEFAULT:config_dir}/calibration_mat_generator_modules/pcd_evaluation_value_20m10m_origin0.npy]
# 設定値：入力座標(x_i,y_i) -> 参照座標(x_r,y_r) への一次変換係数
lid_valmat_coord_A_X = [10,10,10]
lid_valmat_coord_B_X = [100,100,100]
lid_valmat_coord_A_Y = [10,10,10]
lid_valmat_coord_B_Y = [0,0,0]
# 設定値4：デフォルト値（範囲外参照時に返す）
lid_valmat_val_DEFAULT = [10000,10000,10000]

# 座標に対する作業エリア定義mat（白黒画像）のパス
lid_workareadef_img_path = [${DEFAULT:config_dir}/calibration_mat_generator_modules/pcd_workarea_def.png,${DEFAULT:config_dir}/calibration_mat_generator_modules/pcd_workarea_def.png,${DEFAULT:config_dir}/calibration_mat_generator_modules/pcd_workarea_def.png]
# 設定値：入力座標(x_i,y_i) -> 参照座標(x_r,y_r) への一次変換係数
lid_workareadef_img_coord_A_X = [1,1,1]
lid_workareadef_img_coord_B_X = [6,6,6]
lid_workareadef_img_coord_A_Y = [1,1,1]
lid_workareadef_img_coord_B_Y = [0,0,0]
lid_workareadef_img_coord_A_ETA = [1,1,1]
lid_workareadef_img_coord_B_ETA = [0,0,0]
# 設定値4：デフォルト値（範囲外参照時に返す）
lid_workareadef_img_val_DEFAULT = [0,0,0]

[Calib2d3d_CalcProgress]
areadefinition_filepath_c0 = ${DEFAULT:config_dir}/calibration_mat_generator_modules/camera0_progressCalc_area.json
areadefinition_filepath_c1 = ${DEFAULT:config_dir}/calibration_mat_generator_modules/camera1_progressCalc_area.json
areadefinition_filepath_c2 = ${DEFAULT:config_dir}/calibration_mat_generator_modules/camera2_progressCalc_area.json
# 実際に読み込んでいるのはこちら↓
areadefinition_filepathes = [${Calib2d3d_CalcProgress:areadefinition_filepath_c0},${Calib2d3d_CalcProgress:areadefinition_filepath_c1},${Calib2d3d_CalcProgress:areadefinition_filepath_c2}]
progress_threshold = 0.7

# サブブロック進捗表示出力の上書きソース（none/block/group。規定値group）
subblock_overwrite_src = block

[Calib2d3d_CalcCorrespondence]
postprocess_mat = ${DEFAULT:config_dir}/calibration_mat_generator_modules/Rxinv_mat.txt
#校正計算方法　old（従来通りのopencv solvePnP/PnPRansac） / opt（最適化を使った手法）
calcmethod = opt

#以降最適化法使用時のみ使用
#opt_lambda_r = [19,57,19]
opt_lambda_center_r = [0,0,0]
opt_lambda_center_t = [0.0,0.0,0.0]
opt_lambda_axis_r = [0,0,0]
opt_lambda_axis_t = [0.0,0.0,0.0]
optparam_initialvector = ${DEFAULT:config_dir}/calibration_mat_generator_modules/calib_optparam_scx900.json

#mode [C,X][Y,L,E,N] C:bbox中心 X:頭・足座標 Y:全有効 L:エリア内有効 E:エリア内無効 N:無効 CL-XEのように使用(内部的には文字列検索)
corrpoint_mode = CL-XE
enable_recalc_center3d_z = True

use_centerpoint_x_min = [-10.0, 3.0, -10.0]
use_centerpoint_x_max = [10.0, 7.3, 10.0]
use_centerpoint_y_min = [-5.075, -10.0, 2.075]
use_centerpoint_y_max = [-2.075, 10.0, 5.075]

#mode [Y,L,E,N] Y:全有効 L:エリア内有効 E:エリア内無効 N:無効 上記で作った対応点の中でエリア内外特定の対応点のみを使用
corner_rangefilter_mode = E
corner_rangefilter_x_min = [-10.0, 3.0, -10.0]
corner_rangefilter_x_max = [10.0, 5.8, 10.0]
corner_rangefilter_y_min = [-5.075, -10.0, 1]
corner_rangefilter_y_max = [-1, 10.0, 5.075]

bbox_center3d_z_ratio = 0.7

[Calib2d3d_CalcAccuracy]
check_enable = False

[Facade]
# 共有メモリ全域に未初期化を示すパターン BAADFOODを書き込む。とても速度低下するためバグチェック用
write_dummydata = False

[Calib3d3d_CalibParams]
# 理想的なLiDAR設置位置
# lidar0を基準LiDARとする
lidar0_calib_path = ./calibration/3d-3d_ideal_position/lidar2crane_trans_mat_0.csv
lidar1_calib_path = ./calibration/3d-3d_ideal_position/lidar2crane_trans_mat_1.csv
lidar2_calib_path = ./calibration/3d-3d_ideal_position/lidar2crane_trans_mat_1.csv
lidar3_calib_path = ./calibration/3d-3d_ideal_position/lidar2crane_trans_mat_1.csv
lidar4_calib_path = ./calibration/3d-3d_ideal_position/lidar2crane_trans_mat_1.csv
lidar5_calib_path = ./calibration/3d-3d_ideal_position/lidar2crane_trans_mat_1.csv
lidars_calib_path = [${lidar0_calib_path},${lidar1_calib_path}]
voxel_size_for_ground_pts = 0.5
voxel_size_for_calib = 0.1
crane_profile_path = ${DEFAULT:config_dir}/calibration_mat_generator_modules/crane_profiles.json
# Lidar2LidarにおけるICPの探索範囲[m]、徐々に探索範囲を狭くする
thr_radius_L2L=[2.0, 1.0, 0.5, 0.3, 0.1, 0.05]
# Lidar2CraneにおけるICPの探索範囲[m]。LiDARとクレーンの距離は近いため、探索範囲は狭め
thr_radius_L2C=[0.3, 0.1, 0.05]

[Calib3d3d_NdtParams]
# 2D格子の1辺 [m]。大きいほどロバストで局所解に落ちにくいが精度は落ちる
voxel_size = 5
# 点群を2Dセルに落としたあとのダウンサンプルサイズ
ds_voxel_xy = 0.1
# 1セルを「有効な正規分布」として採用するために必要な最小点数。大きいほど統計が安定するが、有効セルが減って対応が取れなくなる
min_points_per_voxel = 8
# 9近傍(3x3)のうち、評価に使うセル数。小さいほど高速だが境界不連続が出やすい
neighbor_top_k = 9
# マハラノビス距離^2 のゲート。これより大きいセルは「外れ」として重み0にする
# 小さすぎると inliers が減って動かない。大きすぎると外れに引っ張られる
neighbor_maha2_gate = 100.0
# 大きいほど重み分布が平坦になりロバスト（ただし重くなる）
weight_temperature = 1.5
# 幾何重みのスケール。w_geom ∝ exp(-0.5*||p-center||^2 / geom_sigma^2)。voxel_sizeの0.7〜1.0倍が目安。小さすぎると境界で不連続、大きすぎると効果が薄い
geom_sigma = 0.9
# セル中心からの距離ゲート [m]（0なら無効）
geom_gate = 0.0
# 最大反復回数。初期行列がある程度あっているなら10〜30で十分
max_iters = 5
# LMの初期ダンピング。小さいほどGauss-Newton寄りで速いが不安定になりやすい
lm_lambda_init = 1e-2
# 1反復あたりの並進更新量の上限 [m]（tx,tyの2次元ノルムでクリップ）
step_clip_trans = 0.05
# 1反復あたりのyaw更新量上限 [rad]
step_clip_yaw = 2
# NDT校正で使用する点群範囲を設定
range_min = 0.5
range_max = 50.0
# センサが理想に対して回転した状態でつけられている場合の対策（±15度まで対応）
yaw_offset_list = [-15,-12.5,-10,-7.5,-5,-2.5,0,2.5,5,7.5,10,12.5,15]
# _split_and_thin関数でダウンサンプルする点群を選ぶ閾値のマージン。正の値だと閾値が上空方向に動き、負だと閾値が地面方向に動く
# 閾値 = 基準値 + マージン値 (基準値はapp_config.General.ground_heightの値)
thinning_margin = 0.5

[Calib3d3d_SimParams]
# シミュレーションにおけるLiDAR計測範囲[m]
max_range = 10.0
# LiDARの種類(airy or mid360): mid360しか使わない
lidar_type = mid360

# 回転式LiDAR用パラメータ(今はAiry用だが、OS0やQT128もパラメータを変えたら対応可能)
rays_az = 240
rays_el = 120
vfov = [-90.0, 90.0]

# mid360の配光パターンを保存したCSV
mid360_laser_pattern_path = ${DEFAULT:config_dir}/calibration_mat_generator_modules/laser_pattern/mid360.csv
# 上の配光パターンを何秒分読み込むか（最大8秒）
points_accum_time = 8

[CalibCheck2d3d]
onnx_model_path = ./checkpoints/damoyolo_tinynasL45_L_3.onnx
camera_intrinsics_path = "./calibration/camera_intrinsics_MCDE7180A.json"

lidar_calib_files = [${Filepath_IO:CalibCheck3d3dmat_lid0},${Filepath_IO:CalibCheck3d3dmat_lid1}]
camera_calib_files = [${Filepath_IO:CalibCheck2d3dmat_cam0},${Filepath_IO:CalibCheck2d3dmat_cam1},${Filepath_IO:CalibCheck2d3dmat_cam2}]
new_axis_mode = True
image_w = 1920
image_h = 1080
z_threshold = -1.0
camera_count = 3
score_accept_count_threshold = 5
score_value_threshold = 0.10
resultfiles = [${Filepath_IO:resultfiles_camera0},${Filepath_IO:resultfiles_camera1},${Filepath_IO:resultfiles_camera2}]
