"""

Ensure that dependencies are available and then load the extension module.
"""
from __future__ import annotations
from onnxruntime.capi import _ld_preload
import onnxruntime.capi.onnxruntime_pybind11_state
from onnxruntime.capi.onnxruntime_pybind11_state import AdapterFormat
from onnxruntime.capi.onnxruntime_pybind11_state import ArenaExtendStrategy
from onnxruntime.capi.onnxruntime_pybind11_state import EPFail
from onnxruntime.capi.onnxruntime_pybind11_state import EngineError
from onnxruntime.capi.onnxruntime_pybind11_state import ExecutionMode
from onnxruntime.capi.onnxruntime_pybind11_state import ExecutionOrder
from onnxruntime.capi.onnxruntime_pybind11_state import Fail
from onnxruntime.capi.onnxruntime_pybind11_state import GraphOptimizationLevel
from onnxruntime.capi.onnxruntime_pybind11_state import InferenceSession
from onnxruntime.capi.onnxruntime_pybind11_state import InvalidArgument
from onnxruntime.capi.onnxruntime_pybind11_state import InvalidGraph
from onnxruntime.capi.onnxruntime_pybind11_state import InvalidProtobuf
from onnxruntime.capi.onnxruntime_pybind11_state import LoraAdapter
from onnxruntime.capi.onnxruntime_pybind11_state import ModelCompiler
from onnxruntime.capi.onnxruntime_pybind11_state import ModelLoadCanceled
from onnxruntime.capi.onnxruntime_pybind11_state import ModelLoaded
from onnxruntime.capi.onnxruntime_pybind11_state import ModelMetadata
from onnxruntime.capi.onnxruntime_pybind11_state import ModelRequiresCompilation
from onnxruntime.capi.onnxruntime_pybind11_state import NoModel
from onnxruntime.capi.onnxruntime_pybind11_state import NoSuchFile
from onnxruntime.capi.onnxruntime_pybind11_state import NodeArg
from onnxruntime.capi.onnxruntime_pybind11_state import NotFound
from onnxruntime.capi.onnxruntime_pybind11_state import NotImplemented
from onnxruntime.capi.onnxruntime_pybind11_state import OrtAllocatorType
from onnxruntime.capi.onnxruntime_pybind11_state import OrtArenaCfg
from onnxruntime.capi.onnxruntime_pybind11_state import OrtCompileApiFlags
from onnxruntime.capi.onnxruntime_pybind11_state import OrtCompiledModelCompatibility
from onnxruntime.capi.onnxruntime_pybind11_state import OrtDevice
from onnxruntime.capi.onnxruntime_pybind11_state import OrtDeviceMemoryType
from onnxruntime.capi.onnxruntime_pybind11_state import OrtEpAssignedNode
from onnxruntime.capi.onnxruntime_pybind11_state import OrtEpAssignedSubgraph
from onnxruntime.capi.onnxruntime_pybind11_state import OrtEpDevice
from onnxruntime.capi.onnxruntime_pybind11_state import OrtExecutionProviderDevicePolicy
from onnxruntime.capi.onnxruntime_pybind11_state import OrtExternalInitializerInfo
from onnxruntime.capi.onnxruntime_pybind11_state import OrtHardwareDevice
from onnxruntime.capi.onnxruntime_pybind11_state import OrtHardwareDeviceType
from onnxruntime.capi.onnxruntime_pybind11_state import OrtMemType
from onnxruntime.capi.onnxruntime_pybind11_state import OrtMemoryInfo
from onnxruntime.capi.onnxruntime_pybind11_state import OrtMemoryInfoDeviceType
from onnxruntime.capi.onnxruntime_pybind11_state import OrtSparseFormat
from onnxruntime.capi.onnxruntime_pybind11_state import OrtSyncStream
from onnxruntime.capi.onnxruntime_pybind11_state import OrtValue
from onnxruntime.capi.onnxruntime_pybind11_state import OrtValueVector
from onnxruntime.capi.onnxruntime_pybind11_state import RunOptions
from onnxruntime.capi.onnxruntime_pybind11_state import RuntimeException
from onnxruntime.capi.onnxruntime_pybind11_state import SessionIOBinding
from onnxruntime.capi.onnxruntime_pybind11_state import SessionObjectInitializer
from onnxruntime.capi.onnxruntime_pybind11_state import SessionOptions
from onnxruntime.capi.onnxruntime_pybind11_state import SparseBlockSparseView
from onnxruntime.capi.onnxruntime_pybind11_state import SparseCooView
from onnxruntime.capi.onnxruntime_pybind11_state import SparseCsrView
from onnxruntime.capi.onnxruntime_pybind11_state import SparseTensor
from onnxruntime.capi.onnxruntime_pybind11_state import copy_tensors
from onnxruntime.capi.onnxruntime_pybind11_state import create_and_register_allocator
from onnxruntime.capi.onnxruntime_pybind11_state import create_and_register_allocator_v2
from onnxruntime.capi.onnxruntime_pybind11_state import disable_telemetry_events
from onnxruntime.capi.onnxruntime_pybind11_state import enable_telemetry_events
from onnxruntime.capi.onnxruntime_pybind11_state import get_all_operator_schema
from onnxruntime.capi.onnxruntime_pybind11_state import get_all_opkernel_def
from onnxruntime.capi.onnxruntime_pybind11_state import get_all_providers
from onnxruntime.capi.onnxruntime_pybind11_state import get_available_providers
from onnxruntime.capi.onnxruntime_pybind11_state import get_build_info
from onnxruntime.capi.onnxruntime_pybind11_state import get_default_session_options
from onnxruntime.capi.onnxruntime_pybind11_state import get_device
from onnxruntime.capi.onnxruntime_pybind11_state import get_ep_devices
from onnxruntime.capi.onnxruntime_pybind11_state import get_model_compatibility_for_ep_devices
from onnxruntime.capi.onnxruntime_pybind11_state import get_session_initializer
from onnxruntime.capi.onnxruntime_pybind11_state import get_version_string
from onnxruntime.capi.onnxruntime_pybind11_state import has_collective_ops
from onnxruntime.capi.onnxruntime_pybind11_state import is_dlpack_uint8_tensor
from onnxruntime.capi.onnxruntime_pybind11_state import opkernel
from onnxruntime.capi.onnxruntime_pybind11_state import quantize_matmul_2bits
from onnxruntime.capi.onnxruntime_pybind11_state import quantize_matmul_4bits
from onnxruntime.capi.onnxruntime_pybind11_state import quantize_matmul_8bits
from onnxruntime.capi.onnxruntime_pybind11_state import quantize_matmul_bnb4
from onnxruntime.capi.onnxruntime_pybind11_state import quantize_qdq_matmul_2bits
from onnxruntime.capi.onnxruntime_pybind11_state import quantize_qdq_matmul_4bits
from onnxruntime.capi.onnxruntime_pybind11_state import register_execution_provider_library
from onnxruntime.capi.onnxruntime_pybind11_state import register_tensorrt_plugins_as_custom_ops
from onnxruntime.capi.onnxruntime_pybind11_state import schemadef
from onnxruntime.capi.onnxruntime_pybind11_state import set_arena_extend_strategy
from onnxruntime.capi.onnxruntime_pybind11_state import set_cuda_device_id
from onnxruntime.capi.onnxruntime_pybind11_state import set_cudnn_conv_algo_search
from onnxruntime.capi.onnxruntime_pybind11_state import set_default_logger_severity
from onnxruntime.capi.onnxruntime_pybind11_state import set_default_logger_verbosity
from onnxruntime.capi.onnxruntime_pybind11_state import set_do_copy_in_default_stream
from onnxruntime.capi.onnxruntime_pybind11_state import set_global_thread_pool_sizes
from onnxruntime.capi.onnxruntime_pybind11_state import set_gpu_mem_limit
from onnxruntime.capi.onnxruntime_pybind11_state import set_seed
from onnxruntime.capi.onnxruntime_pybind11_state import unregister_execution_provider_library
import os as os
import platform as platform
import warnings as warnings
__all__: list[str] = ['AdapterFormat', 'ArenaExtendStrategy', 'EPFail', 'EngineError', 'ExecutionMode', 'ExecutionOrder', 'Fail', 'GraphOptimizationLevel', 'InferenceSession', 'InvalidArgument', 'InvalidGraph', 'InvalidProtobuf', 'LoraAdapter', 'ModelCompiler', 'ModelLoadCanceled', 'ModelLoaded', 'ModelMetadata', 'ModelRequiresCompilation', 'NoModel', 'NoSuchFile', 'NodeArg', 'NotFound', 'NotImplemented', 'OrtAllocatorType', 'OrtArenaCfg', 'OrtCompileApiFlags', 'OrtCompiledModelCompatibility', 'OrtDevice', 'OrtDeviceMemoryType', 'OrtEpAssignedNode', 'OrtEpAssignedSubgraph', 'OrtEpDevice', 'OrtExecutionProviderDevicePolicy', 'OrtExternalInitializerInfo', 'OrtHardwareDevice', 'OrtHardwareDeviceType', 'OrtMemType', 'OrtMemoryInfo', 'OrtMemoryInfoDeviceType', 'OrtSparseFormat', 'OrtSyncStream', 'OrtValue', 'OrtValueVector', 'RunOptions', 'RuntimeException', 'SessionIOBinding', 'SessionObjectInitializer', 'SessionOptions', 'SparseBlockSparseView', 'SparseCooView', 'SparseCsrView', 'SparseTensor', 'copy_tensors', 'create_and_register_allocator', 'create_and_register_allocator_v2', 'disable_telemetry_events', 'enable_telemetry_events', 'get_all_operator_schema', 'get_all_opkernel_def', 'get_all_providers', 'get_available_providers', 'get_build_info', 'get_default_session_options', 'get_device', 'get_ep_devices', 'get_model_compatibility_for_ep_devices', 'get_session_initializer', 'get_version_string', 'has_collective_ops', 'is_dlpack_uint8_tensor', 'kNextPowerOfTwo', 'kSameAsRequested', 'opkernel', 'os', 'platform', 'quantize_matmul_2bits', 'quantize_matmul_4bits', 'quantize_matmul_8bits', 'quantize_matmul_bnb4', 'quantize_qdq_matmul_2bits', 'quantize_qdq_matmul_4bits', 'register_execution_provider_library', 'register_tensorrt_plugins_as_custom_ops', 'schemadef', 'set_arena_extend_strategy', 'set_cuda_device_id', 'set_cudnn_conv_algo_search', 'set_default_logger_severity', 'set_default_logger_verbosity', 'set_do_copy_in_default_stream', 'set_global_thread_pool_sizes', 'set_gpu_mem_limit', 'set_seed', 'unregister_execution_provider_library', 'warnings']
kNextPowerOfTwo: onnxruntime.capi.onnxruntime_pybind11_state.ArenaExtendStrategy  # value = <ArenaExtendStrategy.kNextPowerOfTwo: 0>
kSameAsRequested: onnxruntime.capi.onnxruntime_pybind11_state.ArenaExtendStrategy  # value = <ArenaExtendStrategy.kSameAsRequested: 1>
