# Godot UIアプリ向け 現在送信が反映されていないデータの手動設定用ファイル。毎ループ読み込んでいる為即座に反映される。
#全てDEFAULT上に配置

[DEFAULT]
#yaw: 0 ~ 359.9（値チェックなし）
yaw = 0
# 校正エラー値：ビットとして読み込み 　コメントアウトで上書き機能無効化（特に更新しなくなるだけ）
#errors_calibcommon_bin = 0

# システムエラー値：ビットとして読み込み　コメントアウトで上書き機能無効化（現在は予期せぬエラーのみ実装）
#errors_system_bin = 0

[CalibCheckOverwrite]
# カメラごとに校正要否確認結果をどの値にするか上書きする（OK状態のみ）不明はそのままにする。値： un(→unknown) / ok / ng / na(→上書きしない) 下記項目コメントアウトで上書き機能無効化
values = [na, na, na]

[CalibStatusOverwrite]
# カメラごとに校正結果をどの値にするか上書きする。値： na(→上書きしない)/ 0~255（0:未実施, 1:OK 2:エラー...） 下記項目コメントアウトで上書き機能無効化
values = [na, na, na]
